import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { NextPageWithLayout } from 'models/common'
import { MainLayout } from '@/components/layout'

const Home: NextPageWithLayout = () => {
	const router = useRouter()

	return (
		<div className={styles.container}>
			<Head>
				<title>Learn Nextjs | Easy Frontend</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className={styles.description}>
				Get started by editing
				<Link href="/posts">
					<a className={styles.code}>posts page</a>
				</Link>
			</div>
		</div>
	)
}

Home.Layout = MainLayout

export default Home
